In [186]:
import pandas as pd
from sklearn.linear_model import SGDRegressor

In [ ]:
df_train = pd.read_csv('train_pp.csv')
df_test = pd.read_csv('test_pp.csv')

model = SGDRegressor(random_state=1,learning_rate='adaptive',loss = 'huber',max_iter=10000,early_stopping=True)
x_train = df_train[['UNDER_CONSTRUCTION','RERA','BHK_NO.','SQUARE_FT','READY_TO_MOVE','RESALE']]
y_train = df_train["TARGET(PRICE_IN_LACS)"]

df_train.head()

,Unnamed: 0,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,0,Owner,-0.468134,-0.682715,-0.44624,0.028558,-0.009731,0.468134,0.27524,"Ksfc Layout,Bangalore",12.969910,77.597960,55.0
1,1,Dealer,-0.468134,-0.682715,-0.44624,0.028558,-0.009744,0.468134,0.27524,"Vishweshwara Nagar,Mysore",12.274538,76.644605,51.0
2,2,Owner,-0.468134,-0.682715,-0.44624,0.028558,-0.009924,0.468134,0.27524,"Jigani,Bangalore",12.778033,77.632191,43.0
3,3,Owner,-0.468134,1.464741,-0.44624,0.028558,-0.009926,0.468134,0.27524,"Sector-1 Vaishali,Ghaziabad",28.642300,77.344500,62.5
4,4,Dealer,2.136139,-0.682715,-0.44624,0.028558,-0.009890,-2.136139,0.27524,"New Town,Kolkata",22.592200,88.484911,60.5

In [188]:
x_test = df_test[['UNDER_CONSTRUCTION','RERA','BHK_NO.','SQUARE_FT','READY_TO_MOVE','RESALE']]
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
df_test["TARGET(PRICE_IN_LACS)"] = y_pred
df_test.head()

,Unnamed: 0,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,0,Owner,-0.463048,-0.680532,-1.605650,0.029064,-0.013512,0.463048,0.266907,"Kamrej,Surat",21.262000,73.047700,21.255899
1,1,Dealer,2.159605,1.469439,-0.449007,0.029064,-0.011959,-2.159605,-3.746625,"Panvel,Lalitpur",18.966114,73.148278,66.682623
2,2,Dealer,-0.463048,-0.680532,-0.449007,0.029064,-0.009173,0.463048,0.266907,"New Town,Kolkata",22.592200,88.484911,49.810350
3,3,Dealer,-0.463048,-0.680532,0.707636,0.029064,-0.008300,0.463048,0.266907,"Kalwar Road,Jaipur",26.988300,75.584600,78.356607
4,4,Owner,-0.463048,-0.680532,-1.605650,0.029064,-0.014211,0.463048,0.266907,"Mai Mandir,Nadiad",22.700000,72.870000,21.254246